dist: trusty
language: c

cache:
  directories:
  - $HOME/.opam

env:
  global:
  - OPAMJOBS="2"
  - OPAMYES="true"
  - OPAMVERBOSE="true"
  matrix:
  - OCAML_VERSION=4.04.1
  - OCAML_VERSION=4.04.2
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.06.0
  - OCAML_VERSION=4.06.1
  - OCAML_VERSION=4.07.0
  - OCAML_VERSION=4.07.1
  - OCAML_VERSION=4.08.0
  - OCAML_VERSION=4.08.1
  - OCAML_VERSION=4.09.0
  - OCAML_VERSION=4.09.1
  - OCAML_VERSION=4.10.0
  - OCAML_VERSION=4.10.1
  - OCAML_VERSION=4.10.2
  - OCAML_VERSION=4.11.0
  - OCAML_VERSION=4.11.1
  - OCAML_VERSION=4.11.2
  - OCAML_VERSION=4.12.0
  - OCAML_VERSION=4.13.0
  - OCAML_VERSION=4.13.1

before_install:
  # Obtain and install opam locally.
  - sudo wget https://github.com/ocaml/opam/releases/download/2.0.0/opam-2.0.0-x86_64-linux -O /usr/bin/opam
  - sudo chmod 755 /usr/bin/opam
  # Initialize the switch.
  - opam init -a --disable-sandboxing --compiler="$OCAML_VERSION"
  - opam update
  - opam switch "$OCAML_VERSION"
  - eval $(opam env)
  - opam install dune>=1.9.0 ppxlib>=0.10.0 stdlib-shims

install:
  - make
  - make install

script:
  - make tests

notifications:
  email:
    - christophe@raffalli.eu
