name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: opam install
      run: |
        sudo add-apt-repository ppa:avsm/ppa
        sudo apt update
        sudo apt install opam
        opam init
    - name: switch 4.09.0
      run: |
        opam switch create 4.09.0
        eval $(opam env)
        opam install dune stdlib-shims
    - name: switch 4.04.1
      run: |
        opam switch create 4.04.1
        eval $(opam env)
        opam install dune stdlib-shims
    - name: build 4.09.0
      run: |
        opam switch 4.09.0
        eval $(opam env)
        make
    - name: build 4.04.1
      run: |
        opam switch 4.04.1
        eval $(opam env)
        make
    - name: test 4.09.0
      run: |
         opam switch 4.09.0
         eval $(opam env)
         make tests
    - name: test 4.04.1
      run: |
         opam switch 4.04.1
         eval $(opam env)
         make tests
