name: CI

on:
  push:
    branches:
    - master
    - release/*

strategy:
  matrix:
    ocaml: [4.04.1, 4.09.0]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: opam install
      run: |
        sudo add-apt-repository ppa:avsm/ppa
        sudo apt update
        sudo apt install opam
        opam init
        opam switch create ${{ matrix.ocaml }}
        eval $(opam env)
        opam install dune stdlib-shims ppxlib
        make

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: opam install
      run: make tests
