name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        sudo add-apt-repository ppa:avsm/ppa
        sudo apt update
        sudo apt install opam
        opam init
        opam switch create 4.09.0
        eval $(opam env)
        opam install dune stdlib-shims ppxlib
        make

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: test
      run: make tests
